use std::fs;
use std::io::Write;
use std::path::PathBuf;

pub mod product;

#[derive(Debug)]
pub enum FixerError {
    Custom(String),
    SerdeJson(serde_json::Error),
    Reqwest(reqwest::Error),
}

impl std::fmt::Display for FixerError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl From<reqwest::Error> for FixerError {
    fn from(value: reqwest::Error) -> Self {
        Self::Reqwest(value)
    }
}

impl From<serde_json::Error> for FixerError {
    fn from(value: serde_json::Error) -> Self {
        Self::SerdeJson(value)
    }
}

impl std::error::Error for FixerError {}

/// Interfaces with the Shopify REST API to keep prices up to date with the proprietary ABC
/// accounting software. This program will only change a Shopify price if the price in ABC is
/// greater than what is currently in Shopify.
#[derive(clap::Parser)]
#[command(version, about, long_about = None)]
pub struct Cli {
    /// Set this to bypass std::out and write logs to log files instead
    #[arg(short, long)]
    pub write_logs: bool,

    /// The path to the "item.data" file generated by report 7-10. Usually C:\ABC Software\Database
    /// Export\Company001\Data\item.data
    #[arg(
        short,
        long,
        default_value = "C:\\ABC Software\\Database Export\\Company001\\Data\\item.data"
    )]
    pub item_data: String,

    /// The path to the "item_posted.data" file generated by report 7-10. Usually C:\ABC Software\Database
    /// Export\Company001\Data\item_posted.data
    #[arg(
        short,
        long,
        default_value = "C:\\ABC Software\\Database Export\\Company001\\Data\\item_posted.data"
    )]
    pub posted_data: String,

    #[arg(short, long = "existing", default_value = "existing.csv")]
    pub existing_products: PathBuf,
}

/// List of supported types of logs
#[non_exhaustive]
pub enum Log {
    /// Used for error messages. "./error.txt"
    Error,

    /// Shows which SKUs were adjusted in Shopify. "./adjusted.txt"
    Adjusted,

    /// Shows which SKUs were not adjusted because the price in ABC and Shopify are the same
    /// already. "./not_adjusted_equal.txt"
    Equal,

    /// Shows which SKUs were not adjusted because the price in Shopify is already greater than
    /// ABC. "./not_adjusted_greater.txt"
    Greater,

    /// Shows which SKUs exist in Shopify but were not found in ABC. "./not_found.txt"
    NotFound,

    /// A list of different ABC products that have the same UPC
    DuplicateAbcUpcs,
}

/// Handles logging info to the proper file or stdout as specified.
///
/// # Arguments
///
/// * `to_stdout` - If `true`, don't write `msg` to any file, but instead write `msg` to stdout
/// using `print!`. Otherwise, write `msg` to the appropriate log file specified by `log`
///
/// * `log` - Which `Log` `msg` should be written to. This will only be relevant if `to_stdout` is
/// `false`
///
/// * `msg` - The message to be logged
///
/// # Returns
///
/// If successful, return unit type
///
/// # Errors
///
/// Will return `std::io::Error` if `to_stdout` is `false` and the required log file could not be
/// opened or written to
pub fn log<S>(to_stdout: bool, log: Log, msg: S) -> Result<(), std::io::Error>
where
    S: Into<String>,
{
    let mut msg_str: String = msg.into();
    msg_str.push('\n');

    let now = chrono::Utc::now();
    let now_formatted = format!("{}", now.format("%Y-%m-%d %H:%M:%S"));

    if to_stdout {
        print!("{} {}", now_formatted, msg_str);
        return Ok(());
    }

    // Something is probably very wrong if the binary has no parent directory, but if it doesn't,
    // switch everything to use the current working directory to be safe(r)
    let log_path_parent = match std::env::current_exe()?.parent() {
        Some(p) => p.to_owned(),
        None => PathBuf::from("."),
    };

    let log_path = match log {
        Log::Adjusted => log_path_parent.join("logs/adjusted.txt"),
        Log::Equal => log_path_parent.join("logs/not_adjusted_equal.txt"),
        Log::Error => log_path_parent.join("logs/error.txt"),
        Log::Greater => log_path_parent.join("logs/not_adjusted_greater.txt"),
        Log::NotFound => log_path_parent.join("logs/not_found.txt"),
        Log::DuplicateAbcUpcs => log_path_parent.join("logs/duplicate_abc_upcs.txt"),
    };

    if !log_path_parent.join("logs").exists() {
        fs::create_dir(log_path_parent.join("logs"))?;
    }

    let mut log_file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(log_path)?;
    log_file.write(format!("{} {}", now_formatted, msg_str).as_bytes())?;

    Ok(())
}
