name: "Test, Build, and Release"

permissions:
  contents: write

on: 
  push:
    tags: 
      - "v*"
  workflow_dispatch:

jobs:
  test-build-release: 
    strategy:
      matrix:
        arch:
          - x86_64
        target: 
          - unknown-linux-gnu
          - unknown-linux-musl
          - pc-windows-gnu
          
    env: 
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 

      - name: Run Unit Tests 
        run: cargo test --verbose 

      - name: Install Build Deps
        run: |
          apt update -y && \
          apt install -y pkg-config openssl

      - name: Setup Rust 
        uses: actions-rs/toolchain@v1 
        with: 
          toolchain: stable 
          target: ${{ matrix.arch }}-${{ matrix.target }}

      - name: Compile Project
        run: |
          cargo build --release --target ${{ matrix.arch }}-${{ matrix.target }}

      - name: Tag Release 
        uses: softprops/action-gh-release@v2
        with: 
          draft: false 
          prerelease: false
          make_latest: true
          files: |
            ./target/${{ matrix.arch }}-${{ matrix.target }}/release/shopify-price-fixer{,.exe}
